- app/index.html
- app/scripts/app.js
- app/scripts/controllers/docente/tgs/revision_documento.js
- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/directives/documento/revision_documento.js
- app/views/estudiante/revision_documento.html
- test/karma.conf.js
- test/spec/controllers/estudiante/revision_documento.js
revision por parte de estudiante y como solicitar revisiones
> revision por parte de estudiante y como solicitar revisiones

- app/index.html
- app/scripts/app.js
- app/scripts/controllers/about.js
- app/scripts/controllers/materias_posgrado/listar_solicitudes.js
- app/scripts/controllers/menu.js
- app/scripts/services/config.js
- app/scripts/services/configuration_service.js
- app/scripts/services/token.js
- app/views/about.html
- app/views/materias_posgrado/listar_solicitudes.html
- package-lock.json
- test/spec/services/configuration_service.js
Se modifican opciones de listar solicitudes y se modifica rama de autenticacion
> Autenticacion

- app/index.html
- app/scripts/app.js
- app/scripts/controllers/about.js
- app/scripts/controllers/materias_posgrado/listar_solicitudes.js
- app/scripts/controllers/menu.js
- app/scripts/services/config.js
- app/scripts/services/configuration_service.js
- app/scripts/services/token.js
- app/views/about.html
- app/views/materias_posgrado/listar_solicitudes.html
- package-lock.json
- test/spec/services/configuration_service.js
Para poder continuar con el desarrollo de la modalidad de materias de posgrado
> Merge materias posgrado

- app/index.html
- app/scripts/app.js
- app/scripts/controllers/materias_posgrado/listar_solicitudes.js
- app/scripts/controllers/materias_profundizacion/seleccion_admitidos.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/environment/environment.js
- app/scripts/environment/environment_prod.js
- app/scripts/environment/environment_test.js
- app/scripts/services/documento_crud_services.js
- app/scripts/services/implicit_token.js
> merge de develop con release

- app/scripts/controllers/administracion/parametrizacion.js
Se cambio la consulta del crud y se realizo la limpieza del logs
> Fix: Solucion de consulta con crud y limpieza de logs

- app/index.html
- app/scripts/app.js
- app/scripts/controllers/menu.js
- app/scripts/decorators/text_translate.js
- app/scripts/environment/environment.js
- app/scripts/environment/environment_prod.js
- app/scripts/environment/environment_test.js
- app/scripts/services/config.js
- app/scripts/services/implicit_token.js
Se arreglo el acceso al sistema por parte de google, para poder tener la obtención de roles y generación de menús, también se arreglo mensaje de vista de cliente
> Fix: Se arregla el sistema de autenticacion por google y parte visual del cliente

- app/index.html
- app/scripts/app.js
- app/scripts/controllers/administracion/parametrizacion.js
- app/scripts/controllers/menu.js
- app/scripts/decorators/text_translate.js
- app/scripts/environment/environment.js
- app/scripts/environment/environment_prod.js
- app/scripts/environment/environment_test.js
- app/scripts/services/config.js
- app/scripts/services/implicit_token.js
Se arreglo el acceso al sistema por parte de google, para poder tener la obtención de roles y generación de menús, también se arreglo mensaje de vista de cliente
> Fix :  se hacer merge para arreglar el inconveniente de autenticacion por google y error en el interfaz

- app/scripts/services/implicit_token.js
Se elimina log que muestra información de usuarios
> Fix: Se elimina log

- app/scripts/environment/environment_prod.js
Se arregla el end point de sesion para produccion
> Fix: se cambio el endpoint de sesion de versionamiento

- app/scripts/environment/environment_prod.js
- app/scripts/services/implicit_token.js
Se arregla el endpoint para producción de sesiones con respecto al versionamiento
> Fix : Se arregla el endpoint de sesiones con respecto al versionamiento

- app/scripts/environment/environment_prod.js
- app/scripts/services/implicit_token.js
Se cambia el guardado de código para que se pueda acceder a los servicios por medio de autenticacion por google
> Fix: Se cambia parte del implicit token para que no guarde el codigo sino el documento

- app/scripts/environment/environment_prod.js
- app/scripts/services/implicit_token.js
Se cambia el guardado de datos en implicit token para que guarde el documento más no el codigo cuando se ingresa por google
> Fix : Se cambia el guardado de datos en implicit token para que guarde el documento más no el codigo

- app/scripts/environment/environment_prod.js
se arregla la version de sesiones , puesto el puerto de v2 , el puerto de v2 es 8107 , pero a este apunta es la v1 , por lo cual al colocarla , apunta a la v2
> Fix : se arregla la version de sesiones , puesto el puerto de v2 es diferente

- app/scripts/environment/environment_prod.js
Se agrega el logout para cuando se cierra sesion
> Fix : Se agrega el logout para cuando se cierra sesion

- app/scripts/environment/environment_prod.js
Se arregla el logout para google , pues habia un fallo de 500
> Fix: Se arregla el logout para google

- .drone.yml
Se cambio el paso de build en drone basado en resoluciones por el cambio de librerias
> Fix:  se coloco nuevo build para el drone por el cambio de librerias basado en resoluciones

- .drone.yml
- app/scripts/controllers/reportes/reporte_general.js
- app/scripts/directives/reportes/reportes_spagobi.js
fix: se soluciona el problema de check commits
> fix: se soluciono el problema de check commits

- .drone.yml
se arreglo el drone para el build , partes de vulnerabilidades y cambio de core amazon crud
> fix: se arreglo el drone para el build , partes de vulnerabilidades y cambio de core amazon crud

- app/index.html
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/services/implicit_token.js
- app/views/reportes/reporte_general.html
se arregla para parametros la consulta del servicio core_amazon_crud
> fix: se arregla para parametros la consulta del servicio core_amazon_crud

- .drone.yml
- app/index.html
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/services/implicit_token.js
- app/views/reportes/reporte_general.html
se arregla el cambio a parametros de la api core_amazon_crud
> fix: se arregla el cambio a parametros de la api core_amazon_crud

- app/scripts/services/implicit_token.js
See arregla parte de deteccion de codigo a estudiantes
> fix: se arregla parte de deteccion de codigo a estudiantes

- app/scripts/controllers/reportes/reporte_general.js
- app/views/reportes/reporte_general.html
Se desarrolla la parte de reportes para docentes y coordinadores
> feat: Se desarrolla la parte de reportes para docentes y coordinadores

- app/scripts/controllers/reportes/reporte_general.js
- app/scripts/services/implicit_token.js
- app/views/reportes/reporte_general.html
Se realiza el desarrollo de parte de reportes para docentes y coordinadores
> feat: Se realiza el desarrollo de parte de reportes para docentes y coordinadores

- app/views/reportes/reporte_general.html
Se arregla los reportes para que sean publicos
> fix: Se arregla los reportes para que sean publicos

- app/scripts/decorators/text_translate.js
- app/views/reportes/reporte_general.html
Se agrega los translate al modulo de reportes
> feat: Se agrega los translate al modulo de reportes

- app/index.html
- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- test/karma.conf.js
Se arregla aspectos con respecto al guardado de los estados de los trabajos de grado
> fix: Se arregla aspectos con respecto al guardado de los estados de los trabajos de grado

- app/scripts/environment/environment.js
- app/scripts/environment/environment_prod.js
- app/scripts/environment/environment_test.js
se arregla url en tipo local, se coloca gestor en pruebas
> fix: se arregla url en tipo local, se coloca gestor en pruebas

- app/scripts/environment/environment.js
- app/scripts/environment/environment_test.js
se arregla url en tipo local ya que quedo mal pusta previamente, se coloca gestor en pruebas
> fix: se arregla url en tipo local ya que quedo mal pusta previamente, se coloca gestor en pruebas

- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/environment/environment.js
- app/scripts/environment/environment_prod.js
fix: se actualiza la variable de gestor con el token de pruebas
> fix: se actuliza la variable de gestor con el token de pruebas

- app/scripts/environment/environment_test.js
fix: se actuliza la variable de gestor con el token de pruebas
> fix: se actualiza la variable de gestor con el token de pruebas

- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/services/implicit_token.js
se arregla el guardado de la cookies , que impedia el logout del sistema
> fix: se arregla el guardado de la cookies , que impedia el logout del sistema

- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/environment/environment_test.js
- app/scripts/services/implicit_token.js
Se arrregla el guardado de la cookies , que impedia el logout del sistema
> fix: se arrregla el guardado de la cookies , que impedia el logout del sistema

- app/scripts/services/implicit_token.js
Se arregla el problema de salida del sistema
> fix: se arregla el problema de salida del sistema

- app/scripts/services/implicit_token.js
Se arregla la limpieza de localstorage
> fix:Se arregla la limpieza de localstorage

- app/scripts/services/implicit_token.js
Se arregla la limpieza de localstorage debajo del reemplazo
> fix:Se arregla la limpieza de localstorage debajo del reemplazo

- app/scripts/environment/environment.js
- app/scripts/environment/environment_prod.js
- app/scripts/environment/environment_test.js
- app/scripts/services/config.js
- app/scripts/services/implicit_token.js
- app/views/menu.html
Se arregla el logout del cliente
> fix: Se arregla el logout del cliente

- app/scripts/services/implicit_token.js
Se arregla la limpieza de token por autenticacion por google
> fix: Se arregla la limpieza de token por autenticacion por google

- app/scripts/services/implicit_token.js
fix: Se arregla el state del token por google
> fix: Se arregla el state del token por google

- app/scripts/services/implicit_token.js
fix: Se cambia el metodo de lectura de data en id token
> fix: Se cambia el metodo de lectura de data en id token

- app/scripts/services/implicit_token.js
fix: se arregla el logout del sistema
> fix: se arregla el logout del sistema

- app/scripts/services/implicit_token.js
fix:Se  cambia el formato de limpieza de state en pruebas
> fix:Se  cambia el formato de limpieza de state en pruebas

- app/scripts/services/implicit_token.js
Se cambia el formato de limpieza de state en pruebas
> fix: Se cambia el formato de limpieza de state en pruebas

- app/scripts/services/implicit_token.js
> fix: solucion error logout

- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/controllers/general/concepto_tg.js
- app/scripts/controllers/general/registrar_nota.js
- app/scripts/controllers/pasantia/actas_seguimiento.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/directives/documento/revision_documento.js
- app/scripts/services/implicit_token.js
fix: Se arregla el envio de json del gestor documental
> fix: Se arregla el envio de json del gestor documental

- app/scripts/environment/environment_prod.js
fix: Se arregla el endpoint en produccion de academica
> fix: Se arregla el endpoint en produccion de academica

- app/scripts/controllers/menu.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/services/implicit_token.js
fix: Se arregla bugs en la parte de pasantias y en en el logut del sistema
> fix: Se arregla bugs en la parte de pasantias y en en el logut del sistema

- app/scripts/services/notificacion.js
fix:Se arregla el quemado de la información referente a suscripción , previamente era data para pruebas
> fix:Se arregla el quemado de la informacion

- app/scripts/services/implicit_token.js
fix:Se arregla el logout del sistema
> fix:Se arregla el logout del sistema

- app/scripts/controllers/menu.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/services/implicit_token.js
- app/scripts/services/notificacion.js
- app/views/solicitudes/aprobar_solicitud.html
- app/views/solicitudes/crear_solicitud.html
Se adapta el modulo de socializacion para la creacion por parte del docente jurado
> feat: Se adapta el modulo de socializacion para la creacion por aprte del docente jurado

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/directives/cargar_documento.js
- app/scripts/services/implicit_token.js
- app/views/directives/cargar_documento.html
- app/views/solicitudes/aprobar_solicitud.html
feat: Se crea la subida de actas en las respuesta de las solicitudes de socializacion
> feat: Se creaa la subida de actas en las respuesta de las solicitudes de socilizacion

- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/services/implicit_token.js
fix:Se elimina comentario y data quemada en codigo
> fix:Se elimina comentario y data quemada en codigo

- app/scripts/services/implicit_token.js
> fix:Se elimina parte de git

- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/controllers/materias_profundizacion/formalizar_solicitud.js
- app/scripts/controllers/menu.js
- app/scripts/controllers/notificaciones.js
- app/scripts/controllers/pasantia/solicitar_carta.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/directives/cargar_documento.js
- app/scripts/directives/documento/revision_documento.js
- app/scripts/directives/materias/publicar_asignaturas.js
- app/scripts/directives/trabajo_grado/versiones_documentos_tg.js
- app/scripts/environment/environment.js
- app/scripts/services/notificacion.js
- app/views/solicitudes/aprobar_solicitud.html
feat: se agrega el nuevo flujo de director
> feat: se agrega el nuevo flujo de director

- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/environment/environment.js
fix: Se arregla logs y condicional del nuevo flujo
> fix: Se arregla logs y condicional del nuevo flujo

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
fix: Se arregla logs y condicional del nuevo flujo para el director
> fix: Se arregla logs y condicional del nuevo flujo para el director

- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
> fix: Correccion de error al tener multiples solicitudes realizadas

- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
fix: limite de solicitudes y listado de solicitudes para docente
> Merge from develop to release/0.0.1

- app/index.html
- app/scripts/app.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/decorators/text_translate.js
- app/scripts/environment/environment.js
- app/scripts/services/parametros_service.js
- app/views/solicitudes/crear_solicitud.html
feat: Se realiza envío del codigo asociado a los campos de articulo academico y por otra parte se envía el fix para el envío de solicitudes por parte del docente.
> feat: Se realiza envío del codigo asociado a los campos de articulo academico

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/decorators/text_translate.js
- app/scripts/environment/environment_test.js
- app/views/solicitudes/crear_solicitud.html
- Se desarrolla la funcionalidad asociada al guardado de los detalles del articulo académico.
- Se desarrolla la restricción de cambio de modalidad para solo una vez.
> feat: udistrital/polux_cliente#346     Desarrollo_en_base_acuerdo_03

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/decorators/text_translate.js
- app/scripts/environment/environment_test.js
- app/views/solicitudes/crear_solicitud.html
- Se desarrolla la funcionalidad asociada al guardado de los detalles del articulo académico.
- Se desarrolla la restricción de cambio de modalidad para solo una vez.
> feat: https://github.com/udistrital/polux_cliente/issues/346 Desarrollo_en_base_acuerdo_03

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
Merge entre la rama Ajuste_acuerdo_03_Ingeniería y Ajustes_transversales_y_parcialmente_finales.
> Ajuste acuerdo 03 ingenieria

- app/scripts/controllers/general/registrar_nota.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/decorators/text_translate.js
- app/views/general/registrar_nota.html
- app/views/solicitudes/aprobar_solicitud.html
> Revisión evaluador

- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/decorators/text_translate.js
- app/views/solicitudes/crear_solicitud.html
fix: Se realizan correcciones a los textos mostrados en el cliente
> fix: Se realizan correcciones a los textos mostrados en el cliente

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/decorators/text_translate.js
- app/views/solicitudes/aprobar_solicitud.html
feat: Se realizaron los siguientes cambios:
- Se desarrolla la validación al momento de no seleccionar una respuesta en las peticiones.
- Se cambiar los parametros a director interno, para pasantía interna.
- Se deshabilita la sección de documentos asociados a la solicitud.
> Correcciones_salida_a_producción_MVP_ultimos

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/decorators/text_translate.js
- app/views/solicitudes/crear_solicitud.html
- Se crea la nueva novedad para todas las modalidades llamada prorroga, estos datos se guardarán en detalle trabajo grado.
- Se desarrolla el nuevo checkbox para las modalidades en base al texto en negrilla de cada modalidad.
- Se agrega aclaración en campos donde se suben PDF que el sistema no cuenta con versionamiento de documentos.
- Se realiza el desarrollo para los detalles de la pasantía interna, estos serán guardados en la tabla detalle trabajo grado.
> feat: #397 Correcciones_generales_sobre_polux

- app/scripts/controllers/general/registrar_nota.js
> fix: Ajuste para que el codirector no pueda subir nota

- app/scripts/controllers/solicitudes/crear_solicitud.js
fix: Se realiza corrección para que solo se active usen los campos con estado activo tanto en detalle como en detalle_tipo_solicitud.
> fix: Se realiza corrección para que solo se usen los campos activos

- app/scripts/directives/trabajo_grado/versiones_documentos_tg.js
> fix: Detener uso de nuxeo directamente

- package-lock.json
Fix: Se envía una solución para el tema de las alertas críticas del Dependanbot.
> Fix: Se envía una solución para el tema del Dependanbot

- package-lock.json
Fix: Se envía una solución para el tema de las alertas críticas del Dependanbot.
> Fix: Se envía una solución para el Dependanbot

- package-lock.json
- package.json
Fix: Se suben cambios para solucionar las dependencias Críticas y Altas.
> Fix: Se suben cambios para solucionar las dependencias Críticas y Altas.

- package-lock.json
- package.json
Fix: Se envía una solución para el tema de las alertas críticas del Dependanbot
> Fix: Se envía una solución para el tema de las alertas críticas del Dependanbot

- app/views/docente/tgs/revision_documento.html
- app/views/estudiante/revision_documento.html
Aviso_de_subida_de_documentos
- Se agregan avisos al momento de subir un documento en el sistema.
> Fix: udistrital/polux_cliente#371      Aviso_de_subida_de_documentos

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/decorators/text_translate.js
- app/scripts/directives/materias/solicitar_asignaturas.js
- app/views/directives/materias/solicitar_asignaturas.html
- app/views/solicitudes/crear_solicitud.html
> Cambios de materia posgrado (doble solicitud)

- app/scripts/controllers/general/consultar_trabajo_grado.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/views/solicitudes/crear_solicitud.html
Fix: Se corrige lógica manejada para el tema de las solicitudes iniciales.
> Fix: Se corrige logica manejada para el tema de las solicitudes iniciales

- app/scripts/controllers/general/consultar_trabajo_grado.js
- Se realiza el cambio de tipo documento para consultar_trabajo_grado
> feat: udistrital/polux_cliente#437	tipo_documento_consulta_trabajo_grado

- app/scripts/controllers/solicitudes/crear_solicitud.js
- Se corrige el formato JSON que se envía para las areas de conocimiento, solo se enviará el ID de cada una de las areas de conocimiento seleccionadas.
> fix: udistrital/polux_cliente#437	Correccion_areas_conocimiento

- app/scripts/controllers/general/consultar_trabajo_grado.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- Se realiza el cambio del formato en el cual se enviará el área de conocimiento
> Corrección areas de conocimiento

- app/scripts/controllers/general/consultar_trabajo_grado.js
- app/scripts/controllers/general/registrar_nota.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/decorators/text_translate.js
- app/scripts/directives/solicitudes/listar_solicitudes.js
- app/views/directives/solicitudes/listar_solicitudes.html
- app/views/general/consultar_trabajo_grado.html
- Se desarrolla cambio de parametros para consultar_trabajo_grado, y también se avanza con una sección de registrar nota.
> feat:	udistrital/polux_cliente#437	Cambio_parametros_consultar_trabajo_grado_y_registrar_nota

- app/scripts/controllers/general/registrar_nota.js
> feat: Agregar atributos faltantes al subobjeto TrabajoGrado de VinculacionTrabajoGrado

- app/scripts/controllers/solicitudes/listar_solicitudes.js
> fix: Se corrige error al momento de almacenar objetivos #512

- app/scripts/directives/trabajo_grado/versiones_documentos_tg.js
> feat: Se agrega funcionalidad Visualizar Anteproyecto

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/environment/environment.js
- app/views/solicitudes/aprobar_solicitud.html
> feat: Funcionalidad para que el docente evaluador pueda registrar comentarios al responder una solicitud.

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
> fix: Corrección datos tipo modalidad #523

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
> fix: Corrección en el manejo de sincronia de las funciones #544

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/views/solicitudes/aprobar_solicitud.html
> feat: Se agrega funcionalidad para listar, aprobar y rechazar solicitudes por Extensión Pasantía 

- .github/ISSUE_TEMPLATE/template-for-informe.md
- .github/ISSUE_TEMPLATE/template-for-metting--customer-.md
- .github/ISSUE_TEMPLATE/template-for-report.md
Se agregan cambios para aprobación de solicitudes donde se agregan funciones sincronicas y se modifica el flujo de aprobación para la modalidad de pasantía.
> Corrección para enviar tr de solicitud inicial

- app/scripts/controllers/solicitudes/crear_solicitud.js
> fix: Restricción en la creación de solicitudes hasta finalizar el flujo completo

- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/directives/trabajo_grado/versiones_documentos_tg.js
> feat: Se agrega funcionalidad Guardar y Visualizar Documentos Pasantia

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/decorators/text_translate.js
- app/views/directives/solicitudes/listar_solicitudes.html
- app/views/solicitudes/aprobar_solicitud.html
- app/views/solicitudes/crear_solicitud.html
- app/views/solicitudes/listar_solicitudes.html
> Feature: Diseño UX de artículos académicos

- app/scripts/controllers/estudiante/revision_documento.js
> feat: Se cambia el cargue de ARL según nuevo flujo

- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/controllers/pasantia/revision_arl.js
- app/scripts/decorators/text_translate.js
- app/views/estudiante/revision_documento.html
> feat: Funcionalidad para Rechazar ARL 

- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/directives/solicitudes/listar_solicitudes.js
- app/views/directives/solicitudes/listar_solicitudes.html
> fix: Corrección de visualización de Documento y clasificación de Revista

- app/scripts/controllers/pasantia/revision_arl.js
> feat: Cambio del estado de TG al aprobar ARL

- app/scripts/controllers/general/consultar_trabajo_grado.js
- app/scripts/controllers/pasantia/actas_seguimiento.js
- app/scripts/controllers/pasantia/revision_arl.js
> Funcionalidad de subir y visualizar actas de seguimiento

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
> feat: Cargar Hoja de Vida Director Externo en Solicitud Inicial 

- app/scripts/controllers/general/registrar_nota.js
> feature: Visualización del Código del Estudiante en la tabla de Registrar Nota

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
> feat: Solicitud cambio Director Externo 

- app/scripts/controllers/general/consultar_trabajo_grado.js
- app/scripts/controllers/pasantia/actas_seguimiento.js
- app/scripts/controllers/pasantia/revision_arl.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/directives/trabajo_grado/versiones_documentos_tg.js
- app/views/general/consultar_trabajo_grado.html
- app/views/solicitudes/aprobar_solicitud.html
> feat: Cambio código abreviación Pasantía

- app/scripts/controllers/solicitudes/crear_solicitud.js
fix: se realiza cambio para solución de detalles no obligatorios
> fix: se realiza cambio para solución de detalles no obligatorios

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
> fix: Arreglo de cargue de documentos en Solicitud Inicial 

- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/directives/solicitudes/listar_solicitudes.js
- app/views/directives/solicitudes/listar_solicitudes.html
- app/views/solicitudes/listar_solicitudes.html
> feature: Descarga de Documentos #701

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
> feature: Anexos tr_solicitud #714

- app/scripts/controllers/general/consultar_trabajo_grado.js
- app/scripts/controllers/menu.js
- app/scripts/controllers/notificaciones.js
- app/scripts/controllers/reportes/reporte_general.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/services/notificacion.js
- app/views/general/consultar_trabajo_grado.html
- app/views/solicitudes/aprobar_solicitud.html
- app/views/solicitudes/listar_solicitudes.html
> fix: Coordinador_Pregrado a Coordinador #732

- app/views/general/consultar_trabajo_grado.html
> feature: Consultar - Extension Pasantias #740

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/directives/cargar_documento.js
- app/views/directives/cargar_documento.html
- app/views/general/consultar_trabajo_grado.html
- app/views/solicitudes/aprobar_solicitud.html
- app/views/solicitudes/listar_solicitudes.html
> fix: Se corrige la rama de origen para las funcionalidades del rol CONTRATISTA

- app/scripts/controllers/reportes/generar_reportes.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/views/reportes/generar_reportes.html
> feature: Visualización áreas de conocimiento #750

- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/controllers/general/registrar_nota.js
- app/scripts/controllers/pasantia/revision_arl.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/decorators/text_translate.js
- app/scripts/directives/documento/revision_documento.js
- app/scripts/directives/documento/ver_revision.js
- app/scripts/environment/environment.js
- app/scripts/environment/environment_prod.js
- app/scripts/environment/environment_test.js
- app/scripts/services/autenticacion_mid_service.js
- app/scripts/services/implicit_token.js
- app/views/pasantia/revision_arl.html
- app/views/solicitudes/aprobar_solicitud.html
> feat: Se implementa el servicio de notificaciones

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/decorators/text_translate.js
- app/views/solicitudes/crear_solicitud.html
feat: se desarrolla modal para ingreso de datos personales arl issue #760
> feat: se desarrolla modal para ingreso de datos personales arl

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/decorators/text_translate.js
- app/views/solicitudes/aprobar_solicitud.html
Se desarrolla la visualización de data arl para extensión de pasantías isuue #779
> feat: se desarrolla la visualización de data arl para extensión de pasantías

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/decorators/text_translate.js
- app/scripts/directives/solicitudes/listar_solicitudes.js
- app/views/directives/solicitudes/listar_solicitudes.html
- app/views/solicitudes/aprobar_solicitud.html
feat: se crea vista de datos personales para ARL en consultar_proyecto_grado #799
> feat: se crea vista de datos personales para ARL en consultar_proyecto_grado

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/decorators/text_translate.js
- app/scripts/directives/solicitudes/listar_solicitudes.js
- app/views/directives/solicitudes/listar_solicitudes.html
- app/views/solicitudes/aprobar_solicitud.html
feat: se desarrolla vista de datos personales para ARL en consultar_trabajo_grado #799
> feat: se desarrolla vista de datos personales para ARL en consultar_trabajo_grado

- app/scripts/controllers/notificaciones.js
- app/scripts/controllers/reportes/reporte_general.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/views/solicitudes/aprobar_solicitud.html
- app/views/solicitudes/listar_solicitudes.html
> feature: Discriminación Coordinadorde Pregrado y Posgrado #792

- app/scripts/controllers/general/registrar_nota.js
[…jo_grado](fix:se realiza ajuste para solicitud de documentos en documento_trabajo_grado) #808
> fix:se realiza ajuste para solicitud de documentos en documento_trabajo_grado

- app/scripts/controllers/notificaciones.js
- app/scripts/controllers/reportes/reporte_general.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/decorators/text_translate.js
- app/views/solicitudes/aprobar_solicitud.html
- app/views/solicitudes/listar_solicitudes.html
> feature: Estabilización del Cliente para Materias de Posgrado #818

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/directives/materias/solicitar_asignaturas.js
- app/views/solicitudes/crear_solicitud.html
> feature: Nuevo endpoint para cargar Materias y corrección de errores en Modalidad de Posgrado

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
> feature: Envío correcto del payload en la aprobación de solicitudes de Materias de Posgrado

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
> feature: Lógica completa de Materias de Posgrado con Coordinadores Diferentes

- app/scripts/controllers/general/registrar_nota.js
- app/views/general/registrar_nota.html
> feat: Se agrega funcionalidad registro notas posgrado 

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
> feature: Optimización aprobarPosgrado y uso de rootScope #867

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
feat: se desarrolla el flujo de solicitudes de cancelación y cambio de materias en modalidad posgrado #875
> feat:se desarrolla el flujo de solicitudes de cancelación y cambio de materias en modalidad posgrado 

- app/scripts/controllers/general/consultar_trabajo_grado.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/decorators/text_translate.js
- app/views/general/consultar_trabajo_grado.html
> feat: se almacena nombre carrera posgrado

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
> feature: Aprobar Solicitudes Posgrado con rol Contratista #884

- app/scripts/controllers/solicitudes/listar_solicitudes.js
> feature: Proyecto curricular en Cambio de Materias y Cancelación #903

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
- app/scripts/directives/solicitudes/listar_solicitudes.js
> fix: Se corrige estado solicitudes posgrado 

- app/scripts/controllers/solicitudes/listar_solicitudes.js
> feature: Flujo de Materias de Posgrado con Dos Asistentes

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/directives/materias/solicitar_asignaturas.js
- app/views/solicitudes/crear_solicitud.html
> feat: Corrección errores posgrados 

- app/scripts/controllers/general/registrar_nota.js
> feature: Registrar Nota Asistentes #918

- app/scripts/controllers/general/consultar_trabajo_grado.js
- app/scripts/controllers/general/registrar_nota.js
- app/scripts/decorators/text_translate.js
- app/scripts/directives/trabajo_grado/versiones_documentos_tg.js
- app/views/general/registrar_nota.html
feat: se desarrolla cargue y visualización de reporte de notas posgrado #920
> feat: se desarrolla cargue y visualización de reporte de notas posgrado

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
> hotfix: Rol de Contratista en Pregrado #930

- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/controllers/general/consultar_trabajo_grado.js
- app/scripts/controllers/materias_posgrado/listar_aprobados.js
- app/scripts/controllers/materias_posgrado/listar_solicitudes.js
- app/scripts/controllers/materias_posgrado/registrar_nota.js
- app/scripts/controllers/materias_posgrado/solicitar_asignaturas.js
- app/scripts/controllers/materias_profundizacion/listar_solicitudes.js
- app/scripts/controllers/materias_profundizacion/registrar_nota.js
- app/scripts/controllers/materias_profundizacion/seleccion_admitidos.js
- app/scripts/controllers/materias_profundizacion/solicitar_asignaturas.js
- app/scripts/controllers/materias_profundizacion/vincular_admitidos.js
- app/scripts/controllers/pasantia/aprobar_carta.js
- app/scripts/controllers/pasantia/solicitar_carta.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/controllers/trabajo_grado/revisar_anteproyecto.js
- app/scripts/controllers/trabajo_grado/revisar_proyecto.js
- app/scripts/directives/solicitudes/asignar_estudiantes.js
> fix: Corrección consulta datos_estudiante 

- app/scripts/controllers/solicitudes/crear_solicitud.js
> fix: Envio solicitud cambio de materias corregido #940

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
> Coreccion errores pruebas funcionales

- app/scripts/directives/solicitudes/listar_solicitudes.js
> fix: Consultar trabajo de grado y listar solicitudes #940

- app/views/directives/areas/asignar_area.html
> fix: Botón quitar áreas de conocimiento #940

- app/scripts/controllers/estudiante/revision_documento.js
- app/scripts/controllers/general/registrar_nota.js
- app/scripts/controllers/pasantia/revision_arl.js
- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/directives/documento/revision_documento.js
- app/scripts/directives/documento/ver_revision.js
> feat: Se habilita el servicio de Notificaciones 

- app/scripts/controllers/solicitudes/crear_solicitud.js
- app/scripts/environment/environment.js
> feat: Creacion de variable de entorno PRODUCCION y ajuste funcionalidad de restricciones

- app/scripts/environment/environment.js
- app/scripts/environment/environment_prod.js
- app/scripts/environment/environment_test.js
> feat: Ajustes variable de entorno en ambiente de produccion 

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
> feat: Se implementa servicio de notificaciones para Materias de Posgrado

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
> feature: Cambios materias de profundización #981

- app/scripts/controllers/solicitudes/listar_solicitudes.js
> feature: Arreglo de Listar Solicitudes en Pregrado y Materias de Profundización

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/crear_solicitud.js
feat: ajustes para solicitudes SCM y SCMA de profundizacion #988
> feat: ajustes para solicitudes SCM y SCMA de profundizacion

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
> feature: Estado al Cancelar con Dos Coordinadores de Pregrado #997

- app/scripts/controllers/solicitudes/aprobar_solicitud.js
- app/scripts/controllers/solicitudes/listar_solicitudes.js
hotfix: se termina de ajustar listar solicitudes para profundización #988
> hotfix: se termina de ajustar listar solicitudes para profundización
